### ISSUE TITLE
Images are Broken

### ISSUE THREAD

**Issue by awsaf49** [subinium/kaggle-badge#3]
I think for some reason badges are showing broken images, 
![image](https://user-images.githubusercontent.com/36858976/151093903-1b3c1fbd-3aa7-447b-8d3b-f3bde95d5a1d.png)
@subinium could you please have a look?

**Comment by subinium** [comment]
Thanks for the error report.

An error occurred in the internal preprocessing due to the case change in the tier information provided by Kaggle. (e.g. grandmaster-> GRANDMASTER).

It has now been fixed, so please check it.

**Comment by awsaf49** [comment]
Thanks
