### ISSUE TITLE
Error Fetching Resource

### ISSUE THREAD

**Issue by r-matsuzaka** [subinium/kaggle-badge#5]
Hi,
I got this error these days.
How can I fix that?

**Comment by subinium** [comment]
sorry for error, i will fix it soon

**Comment by r-matsuzaka** [comment]
Thank you very much!

**Comment by justin-2028** [comment]
The error is still not fixed

Please debug/update the code when you have time :)

**Comment by bibhabasumohapatra** [comment]
it showing none in your readme too . . .when you have time fix it,
great work!!

**Comment by subinium** [comment]
Sorry for late update. 🙏
Fixed.
